"""empty message

Revision ID: 37e330bd5e4c
Revises: 
Create Date: 2019-03-19 13:21:17.442524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37e330bd5e4c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "open_street_map_token",
        sa.Column("osm_uid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=20), nullable=False),
        sa.Column("oauth_token", sa.String(length=48), nullable=False),
        sa.Column("oauth_token_secret", sa.String(length=48), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("osm_uid"),
    )
    op.create_table(
        "profile",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("uphill_max", sa.Float(), nullable=False),
        sa.Column("downhill_max", sa.Float(), nullable=False),
        sa.Column("avoid_curbs", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("profile_id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile")
    op.drop_table("open_street_map_token")
    op.drop_table("user")
    # ### end Alembic commands ###
